import { ScrapedRecipe } from '~/utils/recipeScraper';
import { Recipe } from '~/types/recipe';

/**
 * Estimates recipe difficulty based on cook time and number of steps
 * @param cookTime - Total cook time in minutes
 * @param numSteps - Number of instruction steps
 * @returns Difficulty level: 'Easy', 'Medium', or 'Hard'
 */
export function estimateRecipeDifficulty(
  cookTime: number,
  numSteps: number
): 'Easy' | 'Medium' | 'Hard' {
  if (cookTime < 30 && numSteps < 5) {
    return 'Easy';
  } else if (cookTime > 60 || numSteps > 10) {
    return 'Hard';
  }
  return 'Medium';
}

/**
 * Converts a ScrapedRecipe to the Recipe format used by the store
 * @param scrapedRecipe - Recipe data from scraping/parsing
 * @returns Recipe object without ID (ID is generated by the store)
 */
export function convertScrapedToRecipe(
  scrapedRecipe: ScrapedRecipe
): Omit<Recipe, 'id'> {
  const difficulty = estimateRecipeDifficulty(
    scrapedRecipe.cookTime,
    scrapedRecipe.steps.length
  );

  return {
    userId: '', // Will be set when the recipe is added to the store
    title: scrapedRecipe.title,
    description: scrapedRecipe.description || '',
    ingredients: scrapedRecipe.ingredients,
    steps: scrapedRecipe.steps,
    cookTime: scrapedRecipe.cookTime,
    servings: scrapedRecipe.servings,
    difficulty,
    category: scrapedRecipe.category || 'General',
    tags: scrapedRecipe.tags || [],
    image: scrapedRecipe.image,
    // ChefIQ data if available
    chefiqAppliance: scrapedRecipe.chefiqSuggestions?.suggestedAppliance,
    useProbe: scrapedRecipe.chefiqSuggestions?.useProbe,
    published: false, // New recipes are drafts by default
    status: 'Draft',
  };
}

/**
 * Converts a Recipe back to ScrapedRecipe format
 * Used when passing edited recipes back to preview screens
 * @param recipe - Recipe object from the store
 * @returns ScrapedRecipe object
 */
export function convertRecipeToScraped(recipe: Recipe): ScrapedRecipe {
  return {
    title: recipe.title,
    description: recipe.description || '',
    ingredients: recipe.ingredients,
    steps: recipe.steps,
    cookTime: recipe.cookTime,
    prepTime: 0, // Recipes don't track prepTime separately
    servings: recipe.servings,
    category: recipe.category,
    tags: recipe.tags || [],
    image: recipe.image,
    // Preserve ChefIQ suggestions if available
    chefiqSuggestions: recipe.chefiqAppliance ? {
      suggestedAppliance: recipe.chefiqAppliance,
      suggestedActions: [],
      confidence: 1,
      reasoning: [],
      useProbe: recipe.useProbe,
    } : undefined,
  };
}
